// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package accounts

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEd74d837DecodeGithubComEthereumprojectGoEthereumAccounts(in *jlexer.Lexer, out *AccountJSON) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "address":
			out.Address = string(in.String())
		case "key":
			out.EncryptedKey = string(in.String())
		case "file":
			out.File = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEd74d837EncodeGithubComEthereumprojectGoEthereumAccounts(out *jwriter.Writer, in AccountJSON) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"address\":")
	out.String(string(in.Address))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"key\":")
	out.String(string(in.EncryptedKey))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"file\":")
	out.String(string(in.File))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccountJSON) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEd74d837EncodeGithubComEthereumprojectGoEthereumAccounts(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountJSON) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEd74d837EncodeGithubComEthereumprojectGoEthereumAccounts(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountJSON) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEd74d837DecodeGithubComEthereumprojectGoEthereumAccounts(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountJSON) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEd74d837DecodeGithubComEthereumprojectGoEthereumAccounts(l, v)
}
