builds:
- goos:
  - linux
  - darwin
  - windows
  - freebsd
  goarch:
  - amd64
  - "386"
  main: ./cmd/geth/main.go
  binary: geth
  ldflags: -X main.Version={{.Tag}}
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  # We'll use sed to replace this name with one including commit count
  name_template: 'geth-classic-{{.Tag}}_{{ .Os }}_{{ .Arch }}'
  files:
  # leave files empty, so won't include README or LICENSE in archive, just geth binary
