#!/usr/bin/env bash

counter=0
mkdir -p ./benchmark_keystore200k
for file in ./benchmark_keystore500k/*; do
	if [ $counter -lt 200000 ]; then
		if ! [[ "$file" == *"accounts.db" ]]; then
			cp "$file" ./benchmark_keystore200k/
		fi
	fi
	((counter=counter+1))
done

unset counter
